name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Check build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not found!"
            exit 1
          fi
          echo "Build output found in dist directory"
      - name: List dist directory
        run: ls -R dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: gh-pages-artifact
          path: dist  

  deploy:
    needs: build  # 依赖构建作业
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write  # 部署作业需要独立权限
      id-token: write
    environment:
      name: github-pages  # 关联 GitHub Pages 环境
      url: ${{ steps.deployment.outputs.base_url }}  # 输出部署后的 URL
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3  # 配置 Pages，应在部署作业中
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: gh-pages-artifact
          path: dist  # 将 artifact 解压到 dist 目录
      - name: Check downloaded artifact
        run: |
            echo "Current directory: $(pwd)"
            ls -R
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact: gh-pages-artifact
